# Generated by Django 5.2.5 on 2025-10-09 11:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название отеля')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код отеля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('INACTIVE', 'Неактивный'), ('MAINTENANCE', 'На обслуживании')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('category', models.CharField(choices=[('BUDGET', 'Бюджетный'), ('STANDARD', 'Стандартный'), ('COMFORT', 'Комфорт'), ('BUSINESS', 'Бизнес'), ('LUXURY', 'Люкс'), ('BOUTIQUE', 'Бутик'), ('RESORT', 'Курортный')], default='STANDARD', max_length=20, verbose_name='Категория')),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество звезд')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='Время заезда')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='Время выезда')),
                ('is_auto_confirm', models.BooleanField(default=True, verbose_name='Автоподтверждение бронирований')),
                ('max_advance_days', models.PositiveIntegerField(default=365, verbose_name='Максимальное дней для бронирования вперед')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'category'], name='hotels_hote_status_277830_idx'), models.Index(fields=['city', 'country'], name='hotels_hote_city_a01868_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('MANAGER', 'Менеджер'), ('RECEPTION', 'Ресепшн'), ('RESERVATION', 'Бронирование'), ('ADMIN', 'Администратор'), ('OWNER', 'Владелец')], default='MANAGER', max_length=20, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название типа номера')),
                ('code', models.CharField(max_length=50, verbose_name='Код типа номера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('max_adults', models.PositiveSmallIntegerField(default=2, verbose_name='Макс. взрослых')),
                ('max_children', models.PositiveSmallIntegerField(default=0, verbose_name='Макс. детей')),
                ('max_guests', models.PositiveSmallIntegerField(default=2, verbose_name='Макс. гостей')),
                ('room_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь номера (м²)')),
                ('bed_type', models.CharField(choices=[('SINGLE', 'Односпальная'), ('DOUBLE', 'Двуспальная'), ('TWIN', 'Две односпальные'), ('QUEEN', 'Кровать Queen size'), ('KING', 'Кровать King size'), ('SOFA_BED', 'Диван-кровать'), ('BUNK', 'Двухъярусная')], default='DOUBLE', max_length=20, verbose_name='Тип кровати')),
                ('bed_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество кроватей')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Wi-Fi')),
                ('has_tv', models.BooleanField(default=True, verbose_name='Телевизор')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Кондиционер')),
                ('has_minibar', models.BooleanField(default=False, verbose_name='Минибар')),
                ('has_safe', models.BooleanField(default=True, verbose_name='Сейф')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Балкон')),
                ('is_smoking', models.BooleanField(default=False, verbose_name='Для курящих')),
                ('is_accessible', models.BooleanField(default=False, verbose_name='Доступный для инвалидов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_types/', verbose_name='Фотография номера')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
                'ordering': ['hotel', 'sort_order', 'name'],
                'unique_together': {('hotel', 'code')},
            },
        ),
    ]
